language: node_js
node_js:
  - '9.6.0'
before_script:
  - npm install
script: npm test
before_install:
  - npm i -g npm@6.4.1
cache: npm
after_script: npm test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
