language: node_js
branches:
  only:
    - develop
node_js:
  - '10.9.0'
install:
  - npm install

cache:
  directories:
    - 'node_modules'
script: 
  - NODE_ENV=test npm test
before_script:
  - npm install
after_success:
  - npm run coveralls